# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: wref 0.0.8 ruby lib

Gem::Specification.new do |s|
  s.name = "wref"
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kasper Johansen"]
  s.date = "2015-04-13"
  s.description = "Lightweight weak reference and weak hash that works in 1.9 and JRuby."
  s.email = "k@spernj.org"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/wref.rb",
    "lib/wref/implementations/id_class_unique.rb",
    "lib/wref/implementations/java_weak_reference.rb",
    "lib/wref/implementations/ref.rb",
    "lib/wref/implementations/weak_ref.rb",
    "lib/wref/implementations/weakling.rb",
    "lib/wref/map.rb",
    "shippable.yml",
    "spec/implementations/id_class_unique_spec.rb",
    "spec/implementations/java_weak_reference_spec.rb",
    "spec/implementations/ref_spec.rb",
    "spec/implementations/weak_ref_spec.rb",
    "spec/implementations/weakling_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/garbage_collector_helper.rb",
    "spec/support/map_collection.rb",
    "spec/support/user.rb",
    "spec/support/wref_collection.rb",
    "spec/wref_spec.rb",
    "wref.gemspec"
  ]
  s.homepage = "http://github.com/kaspernj/wref"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.0"
  s.summary = "Weak references and weak hash for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 3.2.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.9.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_development_dependency(%q<highline>, ["~> 1.6.21"])
      s.add_development_dependency(%q<weakling>, [">= 0"])
      s.add_development_dependency(%q<ref>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 3.2.0"])
      s.add_dependency(%q<bundler>, ["~> 1.9.2"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
      s.add_dependency(%q<highline>, ["~> 1.6.21"])
      s.add_dependency(%q<weakling>, [">= 0"])
      s.add_dependency(%q<ref>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 3.2.0"])
    s.add_dependency(%q<bundler>, ["~> 1.9.2"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
    s.add_dependency(%q<highline>, ["~> 1.6.21"])
    s.add_dependency(%q<weakling>, [">= 0"])
    s.add_dependency(%q<ref>, [">= 0"])
  end
end

